### PR TITLE
Fix for latest updates to prompt-toolkit (2.0.7)

### PR DESCRIPTION
**Pull request by Script-Nomad**
Prompt-toolkit made a breaking change to it's layout, moving the `WordCompletion` base class into `prompt-toolkit.completion` causing drupwn to break when prompt-tookit>1.0.15 onwards is installed.

I've implemented a fix that requires the latest prompt-toolkit but does not pin the version so as to not restrict user environments. (Installing in a pipenv is probably the best idea anyway...)

I also took the liberty of setting a default thread count in the parser because the tool runs outrageously slow in enum mode without it. I figured 20 threads was reasonable.

Regards,
-- TrueDemon

### CODE REVIEW

**Comment by immunIT** [comment]
Hi @True-Demon,

Thanks for your pull request! I will check this out ASAP, this should be done this week. Stay tuned for updates.

**Comment by immunIT** [comment]
Hi @True-Demon,  

Could you please pull request towards the develop branch? This will allow me to integrate this change in the next minor release.

Best,

**Comment by True-Demon** [comment]
No problem. Switched to dev branch.

**Comment by immunIT** [comment]
It seems that you forgot to apply your change concerning the prompt-toolkit package in the setup.py.

Below, a screenshot showing the error returned when running the associated docker container.

drupwn

**Comment by True-Demon** [comment]
Sorry about that. I tend to maintain my packages with pip & requirements.txt, so I forgot the setup.py file. It should work now. :+1:

**Comment by immunIT** [comment]
All clear. I'm merging the PR.

**Pull request merged**
